name: Deploy notification-service (PROD)

on:
  push:
    tags:
      - "v*.*.*"
    paths:
      - "notification-service/**"

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service: "notification-service"
      environment: "prod"
