name: Deploy order-service
on:
  push:
    paths:
      - "order-service/**"
jobs:
  call-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service: "order-service"
      environment: "dev"
