name: Deploy notification-service (DEV)

on:
  push:
    branches:
      - main
    paths:
      - "notification-service/**"

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service: "notification-service"
      environment: "dev"
