name: Deploy notification-service (UAT)

on:
  push:
    branches:
      - release/*
    paths:
      - "notification-service/**"

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      service: "notification-service"
      environment: "uat"
